import type { AudienceRole, Evaluation, LlmAdviceResponse } from '../types/api'
import { ROLE_LABEL, t } from '../lib/format'

const ROLES: AudienceRole[] = ['residents', 'farmers', 'managers']

function isLlmSourced(advice: LlmAdviceResponse | null): advice is LlmAdviceResponse {
  return advice !== null && (advice.source === 'llm' || advice.source === 'llm-cache')
}

function SourceBadge({ advice }: { advice: LlmAdviceResponse | null }) {
  if (advice && (advice.source === 'llm' || advice.source === 'llm-cache')) {
    const cached = advice.source === 'llm-cache'
    return (
      <span
        className="inline-flex items-center gap-1 rounded-full border border-violet-200 bg-violet-50 px-2.5 py-0.5 text-xs font-medium text-violet-700"
        title={cached ? 'Generated by DeepSeek for this exact evaluation (served from cache)' : `Generated live by ${advice.model ?? 'DeepSeek'} for this exact evaluation`}
      >
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-3 w-3">
          <path d="M12 3l1.9 5.8a2 2 0 0 0 1.3 1.3L21 12l-5.8 1.9a2 2 0 0 0-1.3 1.3L12 21l-1.9-5.8a2 2 0 0 0-1.3-1.3L3 12l5.8-1.9a2 2 0 0 0 1.3-1.3z"/>
        </svg>
        AI-generated{cached ? ' · cached' : ''}
        {advice.model ? <span className="font-mono text-[10px] text-violet-500">{advice.model}</span> : null}
      </span>
    )
  }
  if (advice?.degraded) {
    return (
      <span
        className="inline-flex items-center gap-1 rounded-full border border-amber-200 bg-amber-50 px-2.5 py-0.5 text-xs font-medium text-amber-700"
        title={advice.detail ?? 'The AI service could not be reached; fixed rule-engine guidance is shown.'}
      >
        AI unavailable · rule-based
      </span>
    )
  }
  return (
    <span
      className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-slate-50 px-2.5 py-0.5 text-xs font-medium text-slate-600"
      title={advice?.message ?? 'Fixed guidance derived from the rule-engine thresholds.'}
    >
      Rule-based guidance
    </span>
  )
}

export function AdvicePanel({
  evaluation,
  llmAdvice,
  adviceLoading = false,
  role,
  onRoleChange,
  onRegenerate,
  regenerating = false,
}: {
  evaluation: Evaluation
  llmAdvice: LlmAdviceResponse | null
  adviceLoading?: boolean
  role: AudienceRole
  onRoleChange: (role: AudienceRole) => void
  onRegenerate?: () => void
  regenerating?: boolean
}) {
  const llm = isLlmSourced(llmAdvice) ? llmAdvice : null
  const roleAdvice = llm?.advice[role]
  const templateItems = evaluation.recommendations[role] ?? []

  return (
    <section className="rounded-2xl border border-slate-200/60 bg-white/80 p-6 shadow-lg shadow-slate-900/5 backdrop-blur">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="flex items-center gap-2">
          <div className={`flex h-8 w-8 items-center justify-center rounded-xl text-white shadow-md ${llm ? 'bg-gradient-to-br from-violet-500 to-fuchsia-600 shadow-violet-500/25' : 'bg-gradient-to-br from-sky-500 to-indigo-600 shadow-sky-500/25'}`}>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4">
              <circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/>
            </svg>
          </div>
          <div>
            <h2 className="text-base font-semibold text-slate-900 sm:text-lg">Action Guidance</h2>
            <p className="text-xs text-slate-500">Decision support — not mandatory instructions</p>
          </div>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <SourceBadge advice={llmAdvice} />
          {onRegenerate ? (
            <button
              type="button"
              onClick={onRegenerate}
              disabled={regenerating || adviceLoading}
              className="inline-flex items-center gap-1 rounded-lg border border-violet-200 bg-violet-50 px-2.5 py-1 text-xs font-medium text-violet-700 transition-all hover:bg-violet-100 disabled:cursor-not-allowed disabled:opacity-50"
              title="Ask the AI model to regenerate the advice for this evaluation"
            >
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={`h-3 w-3 ${regenerating ? 'animate-spin' : ''}`}>
                <path d="M21 12a9 9 0 1 1-2.64-6.36"/><path d="M21 3v6h-6"/>
              </svg>
              {regenerating ? 'Regenerating…' : 'Regenerate'}
            </button>
          ) : null}
        </div>
      </div>
      <div className="mt-3 flex rounded-xl border border-slate-200 bg-white/80 p-0.5 shadow-sm backdrop-blur">
        {ROLES.map((item) => (
          <button
            key={item}
            type="button"
            onClick={() => onRoleChange(item)}
            className={`flex-1 rounded-lg px-3.5 py-1.5 text-sm font-medium transition-all ${
              item === role
                ? 'bg-gradient-to-r from-sky-500 to-indigo-600 text-white shadow-md shadow-sky-500/25'
                : 'text-slate-600 hover:bg-slate-50'
            }`}
          >
            {ROLE_LABEL[item]}
          </button>
        ))}
      </div>
      {llm && roleAdvice ? (
        <div className="mt-4 space-y-3">
          <p className="rounded-xl bg-violet-50/70 p-3.5 text-sm leading-relaxed text-slate-800 ring-1 ring-violet-100">
            {roleAdvice.summary}
          </p>
          <ul className="space-y-3">
            {roleAdvice.actions.map((text, idx) => (
              <li key={idx} className="flex gap-3 rounded-xl bg-slate-50/70 p-3.5 ring-1 ring-slate-100 transition-all hover:bg-slate-50">
                <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-600 text-[11px] font-bold text-white shadow-sm">
                  {idx + 1}
                </span>
                <span className="text-sm leading-relaxed text-slate-800">{text}</span>
              </li>
            ))}
          </ul>
        </div>
      ) : (
        <>
          <p className="mt-3 rounded-xl bg-sky-50/70 p-3 text-xs leading-relaxed text-sky-900 ring-1 ring-sky-100">
            {adviceLoading
              ? 'Asking the AI model for tailored guidance…'
              : 'Guidance for decision-making, not mandatory instructions. Always combine with local conditions and official management notices.'}
          </p>
          <ul className="mt-5 space-y-3">
            {templateItems.map((text, idx) => (
              <li key={idx} className="flex gap-3 rounded-xl bg-slate-50/70 p-3.5 ring-1 ring-slate-100 transition-all hover:bg-slate-50">
                <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-sky-500 to-indigo-600 text-[11px] font-bold text-white shadow-sm">
                  {idx + 1}
                </span>
                <span className="text-sm leading-relaxed text-slate-800">{t(text)}</span>
              </li>
            ))}
          </ul>
        </>
      )}
    </section>
  )
}
